### ISSUE TITLE
PDF rendering displays full URLs

### ISSUE THREAD

**Issue by willdurand** [TailorDev/monod#140]
Say I have a link in my markdown:

```md
[...] framework [ASAIM](http://github.com/ASaiM/framework) to study [...]
```

The preview renders something like this:

![screen shot 2016-05-02 at 20 05 57](https://cloud.githubusercontent.com/assets/217628/14962906/6a4aff52-10a1-11e6-8ca1-c3aec937059a.png)

But the PDF outputs this:

![screen shot 2016-05-02 at 20 05 44](https://cloud.githubusercontent.com/assets/217628/14962910/752c4b4c-10a1-11e6-8c41-a2bf5f3eab43.png)

Looks not correct to me. Any idea? /cc @bebatut

**Comment by jmaupetit** [comment]
I can reproduce this with both Firefox and Chrome. It's seems like a feature :)

This can be easily fixed with a media-query like:

```css
@media print {
    a:link:after,
    a:visited:after {
        content: "" !important;
    }
}
```

See http://stackoverflow.com/questions/2162929/in-firefox-when-printing-a-page-with-anchor-tags-the-link-location-is-printing
